os:
  - linux

language: php

php:
  - '7.1'

notifications:
  email: false

before_script:
  - cd www
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan cache:clear
  - php artisan key:generate
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  - npm run test
