version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes # Development only Docker
  web:
    build: .
    restart: always
    volumes:
      - .:/var:Z
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db